runtime: python39
service: key-attestation

entrypoint: gunicorn -b :$PORT key_attestation:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

health_check:
  enable_health_check: True
  check_interval_sec: 300
  timeout_sec: 4
  unhealthy_threshold_count: 2
  healthy_threshold_count: 2

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^(.*/)?\.swp$
- ^(.*/)?\.DS_Store$
- ^venv/.*
- ^\.git/.*
- ^\.idea/.*
- ^tests/.*
- ^README\.md
- ^\.gitignore
- ^requirements-dev\.txt
- ^Dockerfile
- ^docker-compose\.yml
