runtime: python39 # Specifies Python 3.9 runtime

handlers:
- url: /play-integrity/classic/verify # Clarified path for existing classic verify
  script: auto
  secure: always

- url: /play-integrity/classic/nonce # Added route for existing classic nonce
  script: auto
  secure: always

- url: /play-integrity/standard/verify # New route for standard verify
  script: auto
  secure: always

# Optional: Specify entrypoint if not using default (main.app)
# For example, if your Flask app instance is named 'my_app' in 'main.py':
# entrypoint: gunicorn -b :$PORT main:my_app

# Standard App Engine settings
instance_class: F1 # Basic instance class, suitable for simple apps
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1 # Start with 1 max instance for a simple app
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

# Health checks (optional but good practice)
health_check:
  enable_health_check: True
  check_interval_sec: 300
  timeout_sec: 4
  unhealthy_threshold_count: 2
  healthy_threshold_count: 2

# Environment variables (if any)
# env_variables:
#   MY_VARIABLE: "my_value"

# Static files (if any)
# - url: /static
#   static_dir: static

# Inbound services (if any, e.g., mail)
# inbound_services:
# - mail

# Skip files section (useful for .pyc, .git, etc.)
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^(.*/)?\.swp$
- ^(.*/)?\.DS_Store$
- ^venv/.*
- ^\.git/.*
- ^\.idea/.*
- ^tests/.*
- ^README\.md
- ^\.gitignore
- ^requirements-dev\.txt
- ^Dockerfile
- ^docker-compose\.yml
