openapi: 3.0.0
info:
  title: Play Integrity API Service
  version: v1
  description: |-
    Provides endpoints for interacting with the Google Play Integrity API.
    Allows clients to request a nonce and verify device integrity tokens.
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com

tags:
  - name: PlayIntegrityClassic
    description: Operations related to the classic Play Integrity API requests.
  - name: PlayIntegrityStandard
    description: Operations related to the standard Play Integrity API requests.

servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /play-integrity/classic/nonce:
    post:
      summary: Create Nonce
      description: |-
        Generates a cryptographically secure nonce, stores it, and returns it.
        This nonce should be used by the client when requesting an integrity token
        from the Play Integrity API.
      operationId: createNonce
      tags:
        - PlayIntegrityClassic
      requestBody:
        description: JSON payload containing the session ID.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - session_id
              properties:
                session_id:
                  type: string
                  description: The session ID to associate with the nonce.
                  example: "session_abc123"
      responses:
        '200':
          description: Nonce created successfully.
          content:
            application/json:
              schema:
                type: object
                required:
                  - nonce
                  - generated_datetime
                properties:
                  nonce:
                    type: string
                    description: The base64 URL-safe encoded nonce.
                    example: "aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890-_"
                  generated_datetime:
                    type: integer
                    format: int64
                    description: The server time in epoch milliseconds when the nonce was generated.
                    example: 1678886400000
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /play-integrity/classic/verify:
    post:
      summary: Verify Integrity Token
      description: |-
        Verifies an integrity token obtained from the client against the Google Play Integrity API.
        The request must include the nonce that was originally provided to the client and the
        integrity token itself.
      operationId: verifyIntegrityToken
      tags:
        - PlayIntegrityClassic
      requestBody:
        description: JSON payload containing the nonce and the integrity token.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nonce
                - token
              properties:
                nonce:
                  type: string
                  description: The nonce that was previously obtained from the /play-integrity/classic/nonce endpoint.
                  example: "aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890-_"
                token:
                  type: string
                  description: The integrity token received from the client (from Play Integrity API).
                  example: "long.integrity.token.string.from.client"
      responses:
        '200':
          description: Integrity token verified successfully. The response is the direct JSON output from the Google Play Integrity API.
          content:
            application/json:
              schema:
                type: object
                required:
                  - tokenPayloadExternal
                properties:
                  tokenPayloadExternal:
                    $ref: '#/components/schemas/TokenPayloadExternal'
        '400':
          description: Bad request. This can be due to a missing JSON payload, missing 'nonce' or 'token' in the request, or a nonce mismatch.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - $ref: '#/components/schemas/NonceMismatchErrorResponse'
        '500':
          description: Internal server error. This can be due to server authentication configuration issues or other failures in verifying the integrity token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /play-integrity/standard/verify:
    post:
      summary: Verify Integrity Token (Standard)
      description: |-
        Verifies an integrity token obtained from the client against the Google Play Integrity API (Standard tier).
        The request must include the nonce that was originally provided to the client and the
        integrity token itself. The Standard API may provide more detailed device and app integrity information.
      operationId: verifyIntegrityTokenStandard
      tags:
        - PlayIntegrityStandard
      requestBody:
        description: JSON payload containing the nonce and the integrity token.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - contentBinding # Changed from requestHash
                - token
              properties:
                contentBinding: # Changed from requestHash
                  type: string
                  description: The original content string from the client app, which will be hashed by the server.
                  example: "some_content_to_be_hashed_by_server"
                token:
                  type: string
                  description: The integrity token received from the client (from Play Integrity API using Standard request).
                  example: "long.standard.integrity.token.string.from.client"
      responses:
        '200':
          description: Integrity token verified successfully using Standard API features. The response is the direct JSON output from the Google Play Integrity API.
          content:
            application/json:
              schema:
                type: object
                required:
                  - tokenPayloadExternal
                properties:
                  tokenPayloadExternal:
                    $ref: '#/components/schemas/TokenPayloadExternal'
        '400':
          description: Bad request. Missing payload, 'nonce'/'token', or nonce mismatch.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - $ref: '#/components/schemas/NonceMismatchErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    TokenPayloadExternal:
      type: object
      description: Contains the decoded integrity verdict from Google Play Integrity API.
      required:
        - requestDetails
        - appIntegrity
        - deviceIntegrity
        - accountDetails
      properties:
        requestDetails:
          type: object
          required:
            - requestPackageName
            - nonce
            - timestampMillis
          properties:
            requestPackageName:
              type: string
              example: "dev.keiji.deviceintegrity"
            nonce:
              type: string
              nullable: true
              example: "aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890-_"
            requestHash:
              type: string
              example: "request_hash_example_for_standard"
            timestampMillis:
              type: integer
              format: int64
              description: Timestamp in epoch milliseconds.
              example: 1678886400123
        appIntegrity:
          type: object
          required:
            - appRecognitionVerdict
            - packageName
            - certificateSha256Digest
            - versionCode
          properties:
            appRecognitionVerdict:
              type: string
              example: "PLAY_RECOGNIZED"
            packageName:
              type: string
              example: "dev.keiji.deviceintegrity"
            certificateSha256Digest:
              type: array
              items:
                type: string
              example: ["sha256_cert_digest"]
            versionCode:
              type: integer
              description: Application version code.
              example: 123
        deviceIntegrity:
          type: object
          required:
            - deviceRecognitionVerdict
          properties:
            deviceRecognitionVerdict:
              type: array
              items:
                type: string
              example: ["MEETS_DEVICE_INTEGRITY"]
            deviceAttributes:
              type: object
              nullable: true
              properties:
                sdkVersion:
                  type: string
                  example: "30"
            recentDeviceActivity:
              type: object
              nullable: true
              properties:
                deviceActivityLevel:
                  type: string
                  example: "LEVEL_2"
        accountDetails:
          type: object
          required:
            - appLicensingVerdict
          properties:
            appLicensingVerdict:
              type: string
              example: "LICENSED"
        environmentDetails:
          type: object
          nullable: true
          properties:
            playProtectVerdict:
              type: string
              example: "NO_ISSUES"
            appAccessRiskVerdict:
              type: object
              nullable: true
              properties:
                appsDetected:
                  type: array
                  items:
                    type: string
                  example: ["com.example.someapp"]
      example:
        requestDetails:
          requestPackageName: "dev.keiji.deviceintegrity"
          nonce: "aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890-_"
          timestampMillis: 1678886400123
        appIntegrity:
          appRecognitionVerdict: "PLAY_RECOGNIZED"
          packageName: "dev.keiji.deviceintegrity"
          certificateSha256Digest: ["sha256_cert_digest"]
          versionCode: 123
        deviceIntegrity:
          deviceRecognitionVerdict: ["MEETS_DEVICE_INTEGRITY"]
        accountDetails:
          appLicensingVerdict: "LICENSED"
        environmentDetails:
          playProtectVerdict: "NO_ISSUES"

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: A message describing the error.
          example: "Failed to generate nonce"
    NonceMismatchErrorResponse:
      type: object
      required:
        - error
        - client_provided_value
        - api_provided_value
      properties:
        error:
          type: string
          description: A message indicating a mismatch (e.g., nonce, or server-hashed contentBinding vs. API's requestHash).
          example: "Server contentBinding hash mismatch"
        client_provided_value:
          type: string
          description: The value provided by the client (e.g. nonce, or the server-generated hash of contentBinding).
          example: "server_hashed_content_binding_example"
        api_provided_value:
          type: string
          description: The value found in the Play Integrity API response (e.g. nonce from API, or requestHash from API).
          example: "api_response_request_hash_example"
        play_integrity_response:
          $ref: '#/components/schemas/TokenPayloadExternal'
  securitySchemes: {}
